### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by ashley-plott** [MorevM/equal-heights#1]
### Question

TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at EqualHeights._getElements (equal-heights.mjs:76:1)
    at equal-heights.mjs:160:1
    at Array.forEach (<anonymous>)
    at EqualHeights._registerElements (equal-heights.mjs:155:1)
    at EqualHeights.add (equal-heights.mjs:337:1)
    at window.onload (app.js:201:18)
    
  The selectors are there as I'm already targeting them with SASS.
  
  this is the initialisation 

    const equalHeights = new EqualHeights();

    equalHeights.add([
        { selector: '.single-barrister__recommendations-single--content' }
    ]);

**Comment by MorevM** [comment]
Good day @ashley-plott,

Can you provide more context, or, ideally, make the reproduction repo?
The behavior you describe is pretty basic, and it should work well.

I've created a repo you can start with: https://stackblitz.com/edit/vitejs-vite-bf6y8z?file=main.js
I see some issue about the height calculation, but there is no error you are pointing out.
